networks:
  external:
    driver: bridge
  internal:
    driver: bridge
    internal: true

services:
  fromzer0-proxy:
    build: './nginx'
    ports:
      - 80:80
      - 443:443
    networks:
      - external
      - internal
    depends_on:
      - fromzer0-server
    volumes:
      - ../data/nginx:/var/log/nginx
  fromzer0-server:
    build: './'
    container_name: fromzer0-server
    ports:
      - 5100:5100
    environment:
      TZ: "KST"
      SERVER_NAME: "fromzer0-server"
      HTTP_PORT: ""
      DB_HOST: "fromzer0-database"
      DB_PORT: ""
      DB_USER: ""
      DB_PASS: ""
      DB_NAME: ""
      REDIS_HOST: "fromzer0-redis"
      REDIS_PORT: ""
      MAILGUN_API_KEY: ""
      TELEGRAM_API_KEY: ""
      JWT_KEY_TTL: ""
      JWT_ISSUER: ""
      ACCESS_TTL: ""
      REFRESH_TTL: ""
    volumes:
      - ../data/storage:/app/storage
    networks:
      - internal
    depends_on:
      - fromzer0-database
      - fromzer0-redis
  fromzer0-database:
    image: "postgres:16"
    container_name: fromzer0-database
    ports:
      - 54320:5432
    environment:
      POSTGRES_DB: ""
      POSTGRES_PASSWORD: ""
      TZ: 'Asia/Seoul'
    networks:
      - internal
    volumes:
      - ../data/db:/var/lib/postgresql/data
  fromzer0-redis:
    image: "redis:7"
    ports:
      - 63790:6379
    networks:
      - internal
